# distillery_model/config/assumptions.yaml
# Single Source of Truth for The Brogue Distillery Financial Model
# Human-readable, version-control friendly configuration.

meta:
  model_version: "2.0"
  author: "Factory Assistant"
  last_updated: "2025-07-07"
  currency: "USD"

# --- SCENARIOS: All assumptions that vary between cases ---
scenarios:
  - name: "Base Case"
    volume:
      y1_bottle_target: 50000
      y2_growth_pct: 0.30
      y3_onwards_growth_pct: 0.25
    pricing:
      tasting_room_per_bottle: 80
      club_per_bottle: 90
      wholesale_fob_per_bottle: 24
      annual_price_increase_pct: 0.03
    channel_mix:
      tasting_room_pct: 0.18
      club_pct: 0.14
      wholesale_pct: 0.68
    cogs_per_bottle:
      raw_spirit: 6.49   # $11/pg * 0.59 pg/btl
      barrel_amortization: 1.25
      packaging: 2.10
      excise_tax: 8.74    # $0.77 state + ($13.50 fed * 0.59 pg/btl)
      freight: 0.65
    opex:
      marketing_pct_of_revenue: 0.08
      g_and_a_pct_of_revenue: 0.05
    capex:
      initial_spend_overrun_pct: 0.0
    financing:
      safe_valuation_cap: 15000000
      safe_discount: 0.20
      series_a_pre_money_valuation: 30000000
      series_a_target_month: 18

  - name: "Upside Case"
    volume:
      y1_bottle_target: 65000
      y2_growth_pct: 0.40
      y3_onwards_growth_pct: 0.35
    pricing:
      tasting_room_per_bottle: 85
      club_per_bottle: 98
      wholesale_fob_per_bottle: 26
      annual_price_increase_pct: 0.04
    channel_mix:
      tasting_room_pct: 0.25
      club_pct: 0.20
      wholesale_pct: 0.55
    cogs_per_bottle:
      raw_spirit: 6.00   # Cheaper spirit contract
      barrel_amortization: 1.20
      packaging: 2.05
      excise_tax: 8.74
      freight: 0.60
    opex:
      marketing_pct_of_revenue: 0.10 # Higher spend to drive growth
      g_and_a_pct_of_revenue: 0.04
    capex:
      initial_spend_overrun_pct: -0.05 # Came in under budget
    financing:
      safe_valuation_cap: 18000000
      safe_discount: 0.20
      series_a_pre_money_valuation: 45000000
      series_a_target_month: 15 # Earlier round due to strong performance

  - name: "Downside Case"
    volume:
      y1_bottle_target: 40000
      y2_growth_pct: 0.15
      y3_onwards_growth_pct: 0.10
    pricing:
      tasting_room_per_bottle: 75
      club_per_bottle: 85
      wholesale_fob_per_bottle: 22
      annual_price_increase_pct: 0.02
    channel_mix:
      tasting_room_pct: 0.12
      club_pct: 0.10
      wholesale_pct: 0.78 # Rely more on wholesale
    cogs_per_bottle:
      raw_spirit: 7.50   # Barrel market spikes
      barrel_amortization: 1.35
      packaging: 2.20
      excise_tax: 8.74
      freight: 0.75
    opex:
      marketing_pct_of_revenue: 0.06 # Cut marketing spend
      g_and_a_pct_of_revenue: 0.06
    capex:
      initial_spend_overrun_pct: 0.15 # Still install chaos
    financing:
      safe_valuation_cap: 12000000
      safe_discount: 0.25
      series_a_pre_money_valuation: 20000000
      series_a_target_month: 24 # Delayed round

# --- CONSTANTS: Assumptions that DO NOT change between scenarios ---
constants:
  general:
    forecast_months: 60
    starting_inventory_barrels: 1358
    bottles_per_barrel: 360
    proof_gallons_per_bottle: 0.59
  financing:
    initial_cash_position: 1500000
    safe_round_investment: 3000000
    series_a_investment: 5000000
    revolver_limit: 500000
    revolver_interest_rate: 0.085
    # Cap Table structure pre-SAFE
    founder_shares: 8000000
    early_investor_shares: 2000000
  capex:
    initial_spend_base: 900000 # Still, chillers, bottling line, etc.
    initial_spend_month: 2
    equipment_depreciation_years: 7
    facility_depreciation_years: 15
  opex:
    rent_y1: 160000
    rent_annual_escalator_pct: 0.03
    utilities_insurance_y1: 140000
    utilities_insurance_growth_pct: 0.03
    payroll_y1_base: 480000
    payroll_benefits_tax_pct: 0.25
    payroll_annual_growth_pct: 0.05
  tax:
    federal_income_tax_rate: 0.21
    oregon_state_income_tax_rate: 0.066
  headcount_plan: # Detailed payroll driver table
    # Position, Base Salary, Start Month
    - ["Founder/Master Distiller", 180000, 1]
    - ["Head of Production", 95000, 1]
    - ["Production Assistant 1", 65000, 3]
    - ["Production Assistant 2", 65000, 6]
    - ["Sales Director", 110000, 2]
    - ["Tasting Room Manager", 75000, 4]
    - ["Tasting Room Staff 1", 45000, 4]
    - ["Tasting Room Staff 2", 45000, 7]
    - ["Admin/Finance", 85000, 2]
